[colors]
bg = "48;2;38;28;28"
fg = "22;24;38;2;218;91;228"
err = "1;31"
s_wayland = "38;2;208;188;255"
s_xorg = "38;2;37;175;255"
s_shell = "38;2;218;91;228"
e_hostname = "38;2;133;19;248"
e_date = "38;2;218;91;228"
e_box = "38;2;190;190;228"
e_header = "4;38;2;218;91;228"
e_user = "38;2;75;75;215"
e_passwd = "4;38;2;245;245;205"
e_badpasswd = "38;2;248;19;48"
e_key = "38;2;48;229;233"

[chars]
# hb = "─"
# vb = "│"
# ctl = "┌"
# ctr = "┐"
# cbl = "└"
# cbr = "┘"

[functions]
# poweroff = F1
# reboot = F2
# fido = NONE
# refresh = F5

[strings]
# f_poweroff = "poweroff"
# f_reboot = "reboot"
# f_fido = "fido"
# f_refresh = "refresh"
# e_user = "user"
# e_passwd = "password"
# s_wayland = "wayland"
# s_xorg = "xorg"
# s_shell = "shell"
# opts_pre = "< "
# opts_post = " >"
# ellipsis = "…"

[behavior]
# include_defshell = true
# timefmt = "%X %x"
refresh_rate = 100
source = "/etc/lidm.env"
source = "/etc/locale.conf"
user_source = ".lidm.env"
